model:
    name: SuperGlueSoftMax
    descriptor_dim: 128
    keypoint_encoder: [32, 64, 128]
    GNN_layer_num: 12
    sinkhorn_iterations: 20
    match_threshold: 0.2
    descriptor_dim: 128

optimizer:
    type: Adam
    kwargs:
        lr: 0.0001
        betas: [0.9, 0.999]
        weight_decay: 0
    schedular_kwargs:
        milestones: [80]
        gamma: 0.1

data:
    train:
        stage: anime
        image_size: [368, 368]
        dstype: contour
        batch_size: 1 
    test:
        stage: anime
        dstype: contour
        # img_root: /mnt/lustre/syli/AnimeRun/interp/data/datasets/test_2k_540p
        # seg_root: /mnt/lustre/syli/AnimeRun/interp/data/datasets/test_2k_540p_segment
testing:
    ckpt_epoch: 40
batch_size: 1
expname: ant_softmax_anime_contour_bsz16
epoch: 500
save_per_epochs: 20
log_per_updates: 1
test_freq: 1
seed: 42